/**
 * Server functions for the "Todo" doctype.
 *
 * Generated by `new:server-fn Todo`. Constructs the real
 * Todo controller class (not a generic Document), so any lifecycle
 * hooks it defines (beforeValidate, afterInsert, ...) actually run — see
 * doctypes/todo/todo.ts.
 *
 * Currently open (optionalAuth). Swap in requireAuth + call
 * assertResourcePermission(...) once you're ready to lock these down — see
 * ../auth.ts.
 */
import { createServerFn } from '@tanstack/react-start';
import type { ListOptions } from 'nodra/orm/crud.js';
import { Todo } from '../../../doctypes/todo/todo.js';
import { getNodra } from '../nodra-app.js';
import { serialise } from '../http.js';
import { optionalAuth } from '../auth.js';

interface GetTodoInput {
  name: string;
}

export const getTodo = createServerFn({ method: 'GET', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((data: GetTodoInput) => data)
  .handler(async ({ data }) => {
    const app = await getNodra();
    const doc = await app.orm.getDoc('Todo', data.name);
    return serialise(doc);
  });

interface ListTodosInput {
  filters?: Record<string, unknown>;
  fields?: string[];
  orderBy?: string;
  limit?: number;
  offset?: number;
}

export const listTodos = createServerFn({ method: 'GET', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((data: ListTodosInput) => data)
  .handler(async ({ data }) => {
    const app = await getNodra();

    const options: ListOptions = {
      limit: data.limit ?? 20,
      offset: data.offset ?? 0,
      ...(data.fields ? { fields: data.fields } : {}),
      ...(data.filters ? { filters: data.filters } : {}),
      ...(data.orderBy ? { orderBy: data.orderBy } : {}),
    };

    const [docs, totalCount] = await Promise.all([
      app.orm.getList('Todo', options),
      app.orm.getCount('Todo', options.filters),
    ]);

    return {
      data: docs.map(serialise),
      meta: { total_count: totalCount, limit: options.limit, offset: options.offset },
    };
  });

interface CreateTodoInput {
  data: Record<string, unknown>;
}

export const createTodo = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: CreateTodoInput) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    const meta = app.registry.get('Todo');

    const doc = new Todo(meta, input.data);
    const inserted = await app.orm.insert(doc); // runs Todo's lifecycle hooks
    return serialise(inserted);
  });

interface UpdateTodoInput {
  name: string;
  data: Record<string, unknown>;
}

export const updateTodo = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: UpdateTodoInput) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    const doc = await app.orm.getDoc('Todo', input.name);

    for (const [key, value] of Object.entries(input.data)) {
      doc.set(key, value);
    }

    const updated = await app.orm.update(doc); // runs Todo's lifecycle hooks
    return serialise(updated);
  });

interface DeleteTodoInput {
  name: string;
}

export const deleteTodo = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: DeleteTodoInput) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    await app.orm.deleteDoc('Todo', input.name);
    return { message: 'ok' as const };
  });

// Suggested query-options wrapper for the UI side (TanStack Query):
//
//   import { queryOptions } from '@tanstack/react-query';
//   export const todosQueryOptions = (opts?: ListTodosInput) =>
//     queryOptions({ queryKey: ['todos', opts], queryFn: () => listTodos({ data: opts ?? {} }) });
