/**
 * `new:server-fn <Doctype>` — app-scoped. Scaffolds
 * `src/server/functions/<slug>.ts` with CRUD server functions for one
 * specific doctype.
 *
 * Deliberately doctype-specific rather than generic (unlike the earlier
 * document.ts, which takes `doctype: string` at the call site and can only
 * ever construct a plain `Document`): this template imports and constructs
 * the doctype's own controller class (e.g. `new Loan(meta, data)`, from
 * `doctypes/<slug>/<slug>.ts`, generated by `new:doctype`). That's not
 * cosmetic — `ORM.insert()`/`update()` call lifecycle hooks
 * (beforeValidate, afterInsert, ...) on whatever class instance you hand
 * it. Pass a plain `Document` and any custom hooks the controller defines
 * silently never run; pass the real class and they do. Nodra has no
 * automatic controller-discovery step (checked loader.ts directly — it
 * only loads *.json, never touches the sibling *.ts), so the caller
 * constructing the right class is the only place this can be wired up.
 */
import type { Command } from 'commander';
import { mkdir, writeFile, access } from 'node:fs/promises';
import path from 'node:path';

function toPascalCase(input: string): string {
  return input
    .trim()
    .split(/[\s_-]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function toSlug(input: string): string {
  return input
    .trim()
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

function toClassName(input: string): string {
  return toPascalCase(input).replace(/\s+/g, '');
}

function toCamelCase(className: string): string {
  return className.charAt(0).toLowerCase() + className.slice(1);
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

function buildServerFnTs(doctypeName: string, className: string, slug: string): string {
  const camel = toCamelCase(className);
  const plural = `${camel}s`; // naive pluralization — rename if the doctype needs better grammar

  return `/**
 * Server functions for the "${doctypeName}" doctype.
 *
 * Generated by \`new:server-fn ${doctypeName}\`. Constructs the real
 * ${className} controller class (not a generic Document), so any lifecycle
 * hooks it defines (beforeValidate, afterInsert, ...) actually run — see
 * doctypes/${slug}/${slug}.ts.
 *
 * Currently open (optionalAuth). Swap in requireAuth + call
 * assertResourcePermission(...) once you're ready to lock these down — see
 * ../auth.ts.
 */
import { createServerFn } from '@tanstack/react-start';
import type { ListOptions } from 'nodra/orm/crud.js';
import { ${className} } from '../../../doctypes/${slug}/${slug}.js';
import { getNodra } from '../nodra-app.js';
import { serialise } from '../http.js';
import { optionalAuth } from '../auth.js';

interface Get${className}Input {
  name: string;
}

export const get${className} = createServerFn({ method: 'GET', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((data: Get${className}Input) => data)
  .handler(async ({ data }) => {
    const app = await getNodra();
    const doc = await app.orm.getDoc('${doctypeName}', data.name);
    return serialise(doc);
  });

interface List${className}sInput {
  filters?: Record<string, unknown>;
  fields?: string[];
  orderBy?: string;
  limit?: number;
  offset?: number;
}

export const list${className}s = createServerFn({ method: 'GET', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((data: List${className}sInput) => data)
  .handler(async ({ data }) => {
    const app = await getNodra();

    const options: ListOptions = {
      limit: data.limit ?? 20,
      offset: data.offset ?? 0,
      ...(data.fields ? { fields: data.fields } : {}),
      ...(data.filters ? { filters: data.filters } : {}),
      ...(data.orderBy ? { orderBy: data.orderBy } : {}),
    };

    const [docs, totalCount] = await Promise.all([
      app.orm.getList('${doctypeName}', options),
      app.orm.getCount('${doctypeName}', options.filters),
    ]);

    return {
      data: docs.map(serialise),
      meta: { total_count: totalCount, limit: options.limit, offset: options.offset },
    };
  });

interface Create${className}Input {
  data: Record<string, unknown>;
}

export const create${className} = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: Create${className}Input) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    const meta = app.registry.get('${doctypeName}');

    const doc = new ${className}(meta, input.data);
    const inserted = await app.orm.insert(doc); // runs ${className}'s lifecycle hooks
    return serialise(inserted);
  });

interface Update${className}Input {
  name: string;
  data: Record<string, unknown>;
}

export const update${className} = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: Update${className}Input) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    const doc = await app.orm.getDoc('${doctypeName}', input.name);

    for (const [key, value] of Object.entries(input.data)) {
      doc.set(key, value);
    }

    const updated = await app.orm.update(doc); // runs ${className}'s lifecycle hooks
    return serialise(updated);
  });

interface Delete${className}Input {
  name: string;
}

export const delete${className} = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: Delete${className}Input) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    await app.orm.deleteDoc('${doctypeName}', input.name);
    return { message: 'ok' as const };
  });

// Suggested query-options wrapper for the UI side (TanStack Query):
//
//   import { queryOptions } from '@tanstack/react-query';
//   export const ${plural}QueryOptions = (opts?: List${className}sInput) =>
//     queryOptions({ queryKey: ['${plural}', opts], queryFn: () => list${className}s({ data: opts ?? {} }) });
`;
}

export function registerNewServerFnCommand(program: Command): void {
  program
    .command('new:server-fn <doctype>')
    .description(
      'Scaffold CRUD server functions for one doctype in ./src/server/functions ' +
        '(requires a matching doctype already created via new:doctype)',
    )
    .action(async (rawName: string) => {
      const doctypeName = toPascalCase(rawName);
      const slug = toSlug(rawName);
      const className = toClassName(rawName);

      const doctypeFile = path.join(process.cwd(), 'doctypes', slug, `${slug}.ts`);
      if (!(await pathExists(doctypeFile))) {
        console.error(
          `Error: doctypes/${slug}/${slug}.ts not found.\n` +
            `Run "new:doctype ${doctypeName}" first — server functions need the ` +
            `controller class to exist so lifecycle hooks actually run.`,
        );
        process.exitCode = 1;
        return;
      }

      const outDir = path.join(process.cwd(), 'src', 'server', 'functions');
      const outPath = path.join(outDir, `${slug}.ts`);

      if (await pathExists(outPath)) {
        console.error(`Error: src/server/functions/${slug}.ts already exists. Aborting.`);
        process.exitCode = 1;
        return;
      }

      await mkdir(outDir, { recursive: true });
      await writeFile(outPath, buildServerFnTs(doctypeName, className, slug), 'utf-8');

      console.log(`Created src/server/functions/${slug}.ts`);
      console.log(
        `  get${className}, list${className}s, create${className}, ` +
          `update${className}, delete${className}`,
      );
    });
}
