/**
 * Server functions for the "Locations" doctype.
 *
 * Generated by `new:server-fn Locations`. Constructs the real
 * Locations controller class (not a generic Document), so any lifecycle
 * hooks it defines (beforeValidate, afterInsert, ...) actually run — see
 * doctypes/locations/locations.ts.
 *
 * Currently open (optionalAuth). Swap in requireAuth + call
 * assertResourcePermission(...) once you're ready to lock these down — see
 * ../auth.ts.
 */
import { createServerFn } from '@tanstack/react-start';
import type { ListOptions } from 'nodra/orm/crud.js';
import { Locations } from '../../../doctypes/locations/locations.js';
import { getNodra } from '../nodra-app.js';
import { serialise } from '../http.js';
import { optionalAuth } from '../auth.js';

interface GetLocationsInput {
  name: string;
}

export const getLocations = createServerFn({ method: 'GET', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((data: GetLocationsInput) => data)
  .handler(async ({ data }) => {
    const app = await getNodra();
    const doc = await app.orm.getDoc('Locations', data.name);
    return serialise(doc);
  });

interface ListLocationssInput {
  filters?: Record<string, unknown>;
  fields?: string[];
  orderBy?: string;
  limit?: number;
  offset?: number;
}

export const listLocationss = createServerFn({ method: 'GET', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((data: ListLocationssInput) => data)
  .handler(async ({ data }) => {
    const app = await getNodra();

    const options: ListOptions = {
      limit: data.limit ?? 20,
      offset: data.offset ?? 0,
      ...(data.fields ? { fields: data.fields } : {}),
      ...(data.filters ? { filters: data.filters } : {}),
      ...(data.orderBy ? { orderBy: data.orderBy } : {}),
    };

    const [docs, totalCount] = await Promise.all([
      app.orm.getList('Locations', options),
      app.orm.getCount('Locations', options.filters),
    ]);

    return {
      data: docs.map(serialise),
      meta: { total_count: totalCount, limit: options.limit, offset: options.offset },
    };
  });

interface CreateLocationsInput {
  data: Record<string, unknown>;
}

export const createLocations = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: CreateLocationsInput) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    const meta = app.registry.get('Locations');

    const doc = new Locations(meta, input.data);
    const inserted = await app.orm.insert(doc); // runs Locations's lifecycle hooks
    return serialise(inserted);
  });

interface UpdateLocationsInput {
  name: string;
  data: Record<string, unknown>;
}

export const updateLocations = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: UpdateLocationsInput) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    const doc = await app.orm.getDoc('Locations', input.name);

    for (const [key, value] of Object.entries(input.data)) {
      doc.set(key, value);
    }

    const updated = await app.orm.update(doc); // runs Locations's lifecycle hooks
    return serialise(updated);
  });

interface DeleteLocationsInput {
  name: string;
}

export const deleteLocations = createServerFn({ method: 'POST', strict: { output: false } })
  .middleware([optionalAuth])
  .validator((input: DeleteLocationsInput) => input)
  .handler(async ({ data: input }) => {
    const app = await getNodra();
    await app.orm.deleteDoc('Locations', input.name);
    return { message: 'ok' as const };
  });

// Suggested query-options wrapper for the UI side (TanStack Query):
//
//   import { queryOptions } from '@tanstack/react-query';
//   export const locationssQueryOptions = (opts?: ListLocationssInput) =>
//     queryOptions({ queryKey: ['locationss', opts], queryFn: () => listLocationss({ data: opts ?? {} }) });
